# docker-compose.yml

version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

